services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ENV_VAR=value

  llm-service:
    build:
      context: ./llm-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./llm-service:/app
    environment:
      - ENV_VAR=value
